default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 5
  port: 5432

development:
  <<: *default
  database: my_house_development

production:
  <<: *default
  database: my_house_production

test:
  <<: *default
  database: my_house_test
