default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  port: 5432

development:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: my_house_development

production:
  <<: *default
  database: <%= ENV["PGDATABASE"] || "railway" %>
  username: <%= ENV["POSTGRES_USER"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["PGHOST"] %>
  port: <%= ENV["PGPORT"] || 5432 %>

test:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: my_house_test
