default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  port: 5432

development:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: my_house_development

production:
  <<: *default
  url: <%= ENV['DATABASE_PUBLIC_URL'] %>

test:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: my_house_test
